title: Bulk Edit
description: >-
  This will update document information for all documents in your current
  search.  Please be sure you have edit access to these documents before running
  this add-on.
type: object
documents:
  - query
properties:
  description:
    title: Description
    type: string
  published_url:
    title: Published URL
    type: string
    format: uri
  related_article:
    title: Related Article URL
    type: string
    format: uri
  source:
    title: Source
    type: string
