title: Move Account
description: |
  This will change the account owner for all documents in your current search. 
  To transfer documents, both users must be a member of at least one shared organization.
  DocumentCloud has a group membership dropdown on the left sidebar. 
  Click on the dropdown  to expand the membership list of the organization. 
  Click on the user you would like to transfer documents to, 
  and copy the digits after their name that appear in the search bar. 
  The organization ID can be found by clicking on the 
  documents for the organization on the left sidebar and copying the 
  digits that follow the name of the organization on the search bar. 
  Your current username can be found at https://account.muckrock.com/ under your name. 
  
  **Warning**:
  This is a destructive action.  You may lose access to all documents affected
  by this Add-On.  This is Add-On is primarily meant for users who have ended
  up with mutliple accounts and would like to consolidate them.  Please be very
  sure you know what you are doing before running this Add-On and [read the full instructions and tips here](https://github.com/MuckRock/documentcloud-move-account-addon#readme).
instructions: >-
  To transfer documents, both users must be a member of at least one shared organization. 
  DocumentCloud has a group membership dropdown on the left sidebar. 
  Click on the dropdown to expand the membership list of the organization. 
  Click on the user you would like to transfer documents to, and copy the digits after their name that appear in the search bar. 
  The organization ID can be found by clicking on the documents for the organization 
  on the left sidebar and copying the digits that follow the name of the organization on the search bar. 
  Your current username can be found at https://account.muckrock.com/ under your name. 
  Warning: This is a destructive action. You may lose access to all documents affected by this Add-On. 
  This is Add-On is primarily meant for users who have ended up with mutliple accounts and would like to consolidate them. 
  Please be very sure you know what you are doing before running this Add-On and [read the full instructions and tips here](https://github.com/MuckRock/documentcloud-move-account-addon#readme).
type: object
documents:
  - query
properties:
  user:
    title: Confirm current username
    type: string
    description: Please type the username of the current user to confirm the operation (i.e. peterparker)
  new_user_id:
    title: Account ID to move documents
    type: integer
    description: The user ID for the account to transfer the documents to (this is a number)
  new_org_id:
    title: New Organization ID
    type: integer
    description: >
      The organization ID for the organization to transfer the documents to (optional, this is a number).
      If this is omitted, the documents will not change organization, even if the new owner is not in their current organization.
      Both the old and new user must be a member of this organization.
required: ["new_user_id", "user"]
categories:
  - bulk
